name: publish

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7
    - uses: TagBites/actions/dotnet-build@master
      with:
        solution: TagBites.Expressions.slnx
    - uses: TagBites/actions/dotnet-test@master
    - uses: TagBites/actions/nuget-publish@master
      with:
        nuget-source: "https://api.nuget.org/v3/index.json"
        nuget-key: "${{ secrets.NUGET_KEY }}"
